enabled-worlds:
  - world
default-world-config:
  #耕地保护
  farm-protection: true
  #阻止更改刷怪笼类型
  prevent-change-spawner: true
  #爆炸保护
  explosion-protection: true
  #阻止交互容器
  prevent-interact-container: false
  #阻止放置方块
  prevent-place: false
  #阻止破坏方块
  prevent-break: false
  #阻止火焰蔓延
  prevent-fire-spread: true
  #是否开启死亡不掉落
  keep-inventory: true
