name: TorosamyProtect
version: '2.0-SNAPSHOT'
main: net.torosamy.torosamyProtect.TorosamyProtect
api-version: '1.13'
authors: [ Torosamy,yweiyang ]
website: https://www.bitlie.net
depend:
  - TorosamyCore
softdepend:
  - Residence