name: TorosamyProtect
version: '1.0-SNAPSHOT'
main: net.torosamy.torosamyProtect.TorosamyProtect
api-version: '1.13'
authors: [ Torosamy,yweiyang ]
website: https://www.torosamy.net
depend:
  - TorosamyCore
softdepend:
  - Residence